### PR TITLE
Build/Compile quick fix - Repair of warnings when running application

### PR DESCRIPTION
**Pull request by CaseyCubed**
### Description
No dedicated JIRA ticket connected to this - Performed a repair on a handful of front end warnings upon compile/build. 

### Solution
- Removed unused assets and commented out variables that had no use in current features (Found that they will be used later, so kept them in the code for now)
- Made front-end code a little cleaner and easier to debug by splitting large lines of codes into several lines for readability. 
- Some blocks still appear in the warnings, despite commenting them out. Other blocks of the functions also return as a warning even though they are functional and are useful for the front end. We will have to live with these warnings for now. 

### Testing
Built, rebuilt, and tested functions if they needed to be removed/changed for the sake of a cleaner build. All functions still work, and all UI remains the same

### CODE REVIEW

**Comment by CaseyCubed** [comment]
NOTE: I sneaked in the booking page for the Calendly API reference.

**Review by kyperbelt — CHANGES_REQUESTED** [review]

**Review by CaseyCubed — COMMENTED** [review]
Changes have been addressed

**Review by CaseyCubed — COMMENTED** [review]
These changes are fine by me!

**Review by CaseyCubed — COMMENTED** [review]
LGTM

**Pull request closed without merging**
