### PR TITLE
Quick changes

### PR DESCRIPTION
**Pull request by jcupler**
### Description
Endpoint changes - now implicitly invoking Jackson behind the senses for serialization /  deserialization of POJPO DTO.

### Testing
Does the project build?
Yes

What else did you do to test this?
Manual testing of endpoint

### CODE REVIEW

**Comment by jcupler** [comment]
image

**Review by ZhouDanny — APPROVED** [review]
Looks good to me, pruned a lot of the code and made it more streamlined. We might go back to use the ResponseEntity to ensure that the response code given is 201 instead of 200.

**Comment by jcupler** [comment]
image

**Review by ZhouDanny — APPROVED** [review]
Looks good, now the POST is properly matching the response code.

**Review by kyperbelt — COMMENTED** [review]
good change

**Pull request merged**
