### PR TITLE
Added Folder structure for project start

### PR DESCRIPTION
**Pull request by kyperbelt**
### Description
Added the initial project structure so that we can begin working on your assigned tasks.

### CODE REVIEW

**Review by Buh-La-Kay — APPROVED** [review]

**Review by Buh-La-Kay — APPROVED** [review]

**Comment by jcupler** [comment]
Open question on folder structure: Are we treating each service as it's own Gradle instance (i.e. `service1/src/package_structure/java_files`, `service2/src/package_structure/java_files`), this being the current structure of the PR, or treat everything as one big Gradle project (i.e. `src/service1/package_structure/java_files`, `src/service1/package_structure/java_files`)?

The former would force microservices, but it would lead to multiple Gradle projects and redundant folder structures if we aren't careful `microservice/src/com/adaptedstrength/microservice`.
The later has a danger being monolothic, but I think we could make it microservice as well, if we treat each package as it's own microservice and that it has it's own main. `src/com/adaptedstrength/microservice1/main`, `src/com/adaptedstrength/microservice2/main`

**Comment by kyperbelt** [comment]
> Open question on folder structure: Are we treating each service as it's own Gradle instance (i.e. `service1/src/package_structure/java_files`, `service2/src/package_structure/java_files`), this being the current structure of the PR, or treat everything as one big Gradle project (i.e. `src/service1/package_structure/java_files`, `src/service1/package_structure/java_files`)?
> 
> The former would force microservices, but it would lead to multiple Gradle projects and redundant folder structures if we aren't careful `microservice/src/com/adaptedstrength/microservice`. The later has a danger being monolothic, but I think we could make it microservice as well, if we treat each package as it's own microservice and that it has it's own main. `src/com/adaptedstrength/microservice1/main`, `src/com/adaptedstrength/microservice2/main`

Good insight Joshua - I thought about this, too, and we could also make a modular gradle project, but I did not see a big enough downside to having each service be its own gradle project. It will help keep things organized and easy to manage when working on a single service/feature and make the responsibility of each service clear and force decoupling explicitly by design (for example, you cannot be tempted to import a class from X service package.)

**Review by CaseyCubed — APPROVED** [review]
This looks great! Lets approve this PR so we can all get this project started.

**Comment by jcupler** [comment]
> Good insight Joshua - I thought about this, too, and we could also make a modular gradle project, but I did not see a big enough downside to having each service be its own gradle project. It will help keep things organized and easy to manage when working on a single service/feature and make the responsibility of each service clear and force decoupling explicitly by design (for example, you cannot be tempted to import a class from X service package.)

Good point. Another benefit is that for each microservice, we only import the Spring modules we actually need. For example, Thyme is needed to serve up the front end stuff, but not for defining the REST endpoints. So, the service for serving up the front end stuff can import Thyme, while the other services don't.

It might mean more pain on building and deploying the project, but we can cross that bridge when we come to it. (Also with workflows).

**Review by jcupler — APPROVED** [review]

**Pull request merged**
